# Generated by Django 2.0.2 on 2018-02-20 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, default=None)),
                ('registerDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=50000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'patients',
                'ordering': ('-registerDate',),
                'get_latest_by': 'registerDate',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField(default=None)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='psychotherapist.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionNo', models.IntegerField()),
                ('sessionDate', models.DateTimeField(default=None, null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, max_length=50000)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='psychotherapist.Patient')),
            ],
        ),
    ]
