# Generated by Django 2.0.2 on 2018-03-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'get_latest_by': 'sessionDate', 'ordering': ('sessionNo',), 'verbose_name_plural': 'sessions'},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='session',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='paymentDate',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
