# Generated by Django 2.0.2 on 2018-03-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0002_auto_20180317_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='paymentDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
