# Generated by Django 2.0.2 on 2018-03-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0003_auto_20180317_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='method',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
