# Generated by Django 2.0.2 on 2018-03-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0004_auto_20180318_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
