# Generated by Django 2.0.2 on 2018-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0005_auto_20180318_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.AddField(
            model_name='patient',
            name='byear',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
