# Generated by Django 2.0.5 on 2018-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0008_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commType', models.CharField(blank=True, max_length=20, null=True)),
                ('rcpt', models.CharField(blank=True, max_length=100, null=True)),
                ('exception', models.TextField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
