# Generated by Django 2.0.5 on 2018-09-20 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0009_communicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
