# Generated by Django 2.0.5 on 2018-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychotherapist', '0010_session_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lastMod',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='lastMod',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
